/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIndexRouteImport } from './routes/results/index'
import { Route as ResultsSearchesIndexRouteImport } from './routes/results/searches/index'
import { Route as ResultsJobsIndexRouteImport } from './routes/results/jobs/index'
import { Route as ResultsSearchesSearchIdRouteImport } from './routes/results/searches/$searchId'
import { Route as ResultsJobsJobIdRouteImport } from './routes/results/jobs/$jobId'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsSearchesIndexRoute = ResultsSearchesIndexRouteImport.update({
  id: '/results/searches/',
  path: '/results/searches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsJobsIndexRoute = ResultsJobsIndexRouteImport.update({
  id: '/results/jobs/',
  path: '/results/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsSearchesSearchIdRoute = ResultsSearchesSearchIdRouteImport.update({
  id: '/results/searches/$searchId',
  path: '/results/searches/$searchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsJobsJobIdRoute = ResultsJobsJobIdRouteImport.update({
  id: '/results/jobs/$jobId',
  path: '/results/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/timeline': typeof TimelineRoute
  '/results/': typeof ResultsIndexRoute
  '/results/jobs/$jobId': typeof ResultsJobsJobIdRoute
  '/results/searches/$searchId': typeof ResultsSearchesSearchIdRoute
  '/results/jobs/': typeof ResultsJobsIndexRoute
  '/results/searches/': typeof ResultsSearchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/timeline': typeof TimelineRoute
  '/results': typeof ResultsIndexRoute
  '/results/jobs/$jobId': typeof ResultsJobsJobIdRoute
  '/results/searches/$searchId': typeof ResultsSearchesSearchIdRoute
  '/results/jobs': typeof ResultsJobsIndexRoute
  '/results/searches': typeof ResultsSearchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/timeline': typeof TimelineRoute
  '/results/': typeof ResultsIndexRoute
  '/results/jobs/$jobId': typeof ResultsJobsJobIdRoute
  '/results/searches/$searchId': typeof ResultsSearchesSearchIdRoute
  '/results/jobs/': typeof ResultsJobsIndexRoute
  '/results/searches/': typeof ResultsSearchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/timeline'
    | '/results/'
    | '/results/jobs/$jobId'
    | '/results/searches/$searchId'
    | '/results/jobs/'
    | '/results/searches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/timeline'
    | '/results'
    | '/results/jobs/$jobId'
    | '/results/searches/$searchId'
    | '/results/jobs'
    | '/results/searches'
  id:
    | '__root__'
    | '/'
    | '/timeline'
    | '/results/'
    | '/results/jobs/$jobId'
    | '/results/searches/$searchId'
    | '/results/jobs/'
    | '/results/searches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimelineRoute: typeof TimelineRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
  ResultsJobsJobIdRoute: typeof ResultsJobsJobIdRoute
  ResultsSearchesSearchIdRoute: typeof ResultsSearchesSearchIdRoute
  ResultsJobsIndexRoute: typeof ResultsJobsIndexRoute
  ResultsSearchesIndexRoute: typeof ResultsSearchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/searches/': {
      id: '/results/searches/'
      path: '/results/searches'
      fullPath: '/results/searches/'
      preLoaderRoute: typeof ResultsSearchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/jobs/': {
      id: '/results/jobs/'
      path: '/results/jobs'
      fullPath: '/results/jobs/'
      preLoaderRoute: typeof ResultsJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/searches/$searchId': {
      id: '/results/searches/$searchId'
      path: '/results/searches/$searchId'
      fullPath: '/results/searches/$searchId'
      preLoaderRoute: typeof ResultsSearchesSearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/jobs/$jobId': {
      id: '/results/jobs/$jobId'
      path: '/results/jobs/$jobId'
      fullPath: '/results/jobs/$jobId'
      preLoaderRoute: typeof ResultsJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimelineRoute: TimelineRoute,
  ResultsIndexRoute: ResultsIndexRoute,
  ResultsJobsJobIdRoute: ResultsJobsJobIdRoute,
  ResultsSearchesSearchIdRoute: ResultsSearchesSearchIdRoute,
  ResultsJobsIndexRoute: ResultsJobsIndexRoute,
  ResultsSearchesIndexRoute: ResultsSearchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
