# COMPUTE
# hpc (bool):                whether the compute environment is local or hpc (disables certain GUI features)
# processors_per_job (int):  how many processors to allocate for each job (job step parallelization)
# max_job_workers (int):     how many maximum job workers at any time (job parallelization)
[compute]
hpc=true
processors_per_job=8
max_job_workers=20

# PARAMETERS
# name (name):  user-friendly name for the parameter
# id (str):     identifier for the parameter, cell for FreeCAD, paramater ID for OpenVSP (
# min (float):  minimum value for the parameter
# max (float):  maximum value for the parameter
[model]
[[model.parameters]]
name="shock_angle"
id="theta23_deg"
min=65
max=75
[[model.parameters]]
name="inlet_mach"
id="M2"
min=2
max=3

# OBJECTIVES
# name:  user-friendly name for the objective
# id:    identifier for the objective, used during objective extraction 
# type:  whether the goal is to minimize or maximize the objective
[optimizer]
[[optimizer.objectives]]
name="Pressure Recovery"
id="pr"
type="maximize"